ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'dbt_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbt_password') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DATABASE', 'ecommerce_analytics') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'analytics_dev') }}"
      threads: "{{ env_var('DBT_THREADS', 4) | int }}"
      keepalives_idle: 0
      search_path: "{{ env_var('POSTGRES_SCHEMA', 'analytics_dev') }}"
      
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DATABASE') }}"
      schema: analytics
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
      keepalives_idle: 0
      search_path: analytics