version: 2

sources:
  - name: raw_data
    description: Raw data from production e-commerce systems
    database: ecommerce_analytics
    schema: public
    
    tables:
      - name: customers
        description: Customer account information from user management system
        columns:
          - name: id
            description: Primary key for customers
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - not_null
              - unique
          - name: first_name
            description: Customer first name
            tests:
              - not_null
          - name: last_name
            description: Customer last name
            tests:
              - not_null
          - name: created_at
            description: Account creation timestamp
            tests:
              - not_null
      
      - name: orders
        description: Order transactions from order management system
        columns:
          - name: id
            description: Primary key for orders
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customers table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'customers')
                  field: id
          - name: order_date
            description: Date when order was placed
            tests:
              - not_null
          - name: status
            description: Current order status
            tests:
              - not_null
              - accepted_values:
                  values: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned']
          - name: total_amount
            description: Total order amount in cents
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: true
      
      - name: order_items
        description: Individual line items within orders
        columns:
          - name: id
            description: Primary key for order items
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'orders')
                  field: id
          - name: product_id
            description: Foreign key to products table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'products')
                  field: id
          - name: quantity
            description: Quantity of product ordered
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
                  inclusive: true
          - name: unit_price
            description: Price per unit in cents
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: true
      
      - name: products
        description: Product catalog from inventory management system
        columns:
          - name: id
            description: Primary key for products
            tests:
              - unique
              - not_null
          - name: name
            description: Product name
            tests:
              - not_null
          - name: category
            description: Product category
            tests:
              - not_null
          - name: price
            description: Current selling price in cents
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: true
          - name: cost
            description: Product cost in cents
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: true