name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_analytics'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    # Staging models - clean and standardize
    staging:
      +materialized: view
      +schema: staging
    
    # Intermediate models - business logic
    intermediate:
      +materialized: ephemeral
    
    # Mart models - final analytics tables
    marts:
      +materialized: table
      +schema: marts
      core:
        +schema: core
      finance:
        +schema: finance

# Global variables
vars:
  start_date: '2024-01-01'
  timezone: 'UTC'

# On-run hooks
on-run-start:
  - "{{ log('Starting dbt run at ' ~ run_started_at, info=true) }}"
  
on-run-end:
  - "{{ log('Completed dbt run at ' ~ run_started_at, info=true) }}"